version: '3.7'

services:
  converter:
    build: converter
    image: rcg_converter:latest
  api:
    build: api
    ports:
      - "5000:5000"
    depends_on:
      - converter
    environment:
      PORT: "5000"
      CORS: "https://robocup.inforser.cl"
    network_mode: "reverse-proxy"
    container_name: api.robocup
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.services.api.loadbalancer.server.port=5000"
      - "traefik.http.routers.api.service=api"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`api.robocup.inforser.cl`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
  simulator:
    build: simulator
    ports:
      - "5500:5500"
    depends_on:
      - api
    environment:
      REACT_APP_SOCKET: "https://api.robocup.inforser.cl"
      REACT_APP_PORT: "5500"
    network_mode: "reverse-proxy"
    container_name: robocup
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.services.simulator.loadbalancer.server.port=5500"
      - "traefik.http.routers.simulator.service=simulator"
      - "traefik.http.routers.simulator.entrypoints=websecure"
      - "traefik.http.routers.simulator.rule=Host(`robocup.inforser.cl`)"
      - "traefik.http.routers.simulator.tls=true"
      - "traefik.http.routers.simulator.tls.certresolver=letsencrypt"